kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app-1-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8
- role: worker
  image: kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8
  extraPortMappings:
   - containerPort: 30053 # expose CoreDNS port to port 53 on the host machine
     hostPort: 53
     protocol: udp
   - containerPort: 30053 # expose CoreDNS port to port 53 on the host machine
     hostPort: 53
     protocol: tcp
networking:
  apiServerAddress: "192.168.56.15"
  apiServerPort: 58350
